# http://docs.travis-ci.com/user/build-configuration/
# http://docs.travis-ci.com/user/languages/python/
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
branches:
    only:
        - master
install:
    - pip install -r requirements.txt
    - pip install -e .
script:
    - pytest
deploy:
    provider: pypi
    user: mozillasecurity
    password:
        secure: wYc7AFbw8u0mN0DznvZxOiulZ0Tm1TPAReUni4evVMpaYyv6AcL6yglSoGfF+0qiUMgJxY9JJGTBnhXs5GUZSbH9dZylTHQmkA+IOcyph+iUsJ263l3eAuGYhdxCeLjNXzQGQK6mS20MqVwThZgn5eHUixhgKrHGZIHCjaCMwpI=
    on:
        tags: true
